apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message
  template:
    metadata:
      labels:
        app: message
    spec:
      containers:
        - image: ninavelikajne/message:34
          name: message
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://fanny.db.elephantsql.com:5432/sewztpca
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: sewztpca
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              value: jviqrny5vLJYogFEeyBhAr7daifOAiwB
          ports:
            - containerPort: 2222
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
            readinessProbe:
              httpGet:
                path: /health/ready
                port: server
              initialDelaySeconds: 20
              periodSeconds: 3
         

---

apiVersion: v1
kind: Service
metadata:
  name: message
spec:
  type: LoadBalancer
  ports:
    - port: 2222
      protocol: TCP
      targetPort: server
  selector:
    app: message
